version: 0.2

phases:
  install:
    runtime-version:
      java: openjdk8
    commands:
      - echo install
  pre_build:
    commands:
      - echo Nothing
  build:
    commands:
      - mvn package
      - echo build
  post_build:
    commands:
      - echo Nothing
artifacts:
  files:
    - target/CCdemo.war
    